name: BuildRankInfo
main: com.github.cmptrzd1592.BuildRankInfo.BuildRankInfo
version: 1.0

commands:
   rankinfo:
      description: This is the global command. Does not display information about the specific ranks if the user does not specify the rank they want to learn about.
      usage: /<command> [rank]
      permission: buildrankinfo.*
      permission-message: You do not have permission to do this.
permissions:
    buildrankinfo.*:
      description: Gives access to all rankinfo commands
      default: true
    buildrankinfo.rankinfo:
      description: Core plugin command
      default: true